parameters:
  lch.maintenance.toggle_maintenance_command.class: Lch\MaintenanceBundle\Command\ToggleMaintenanceCommand

services:
  lch.maintenance.toggle_maintenance_command:
    class: '%lch.maintenance.toggle_maintenance_command.class%'
    arguments: ['%kernel.project_dir%']
    tags:
      - { name: console.command }
    public: false
    lazy: true

  Lch\MaintenanceBundle\Command\ToggleMaintenanceCommand:
    alias: lch.maintenance.toggle_maintenance_command